DATE 15.7.2025

# Machine Learning
Training a model on already existing data and then predicting based on that is known machine learning.
* Rainy or sunny or cloudy or humid


# Type of Machine Learning
* Supervised Machine Learning
* Unsupervised Machine Learning
* Reinforecement Learning

#Supervised Machine Learning :
Labeled data and used for prediction

#Unsupervised Machine Learning
Unlabeled data and used for Pattern recorgnition

**Example:** To check whether a fruit is an apple or a banana.

* Reinforcement Learning : Reward basis learning

**Example:** Games and robotics

#Work Flow of Machine Learning:

* Problem Statement
* Data collection
* Data Cleaning (EDA)
* Model implementation
* Evaluation
* Deployment
* Maintenance
#EDA -- Explorartory data analysis

In [ ]:
import numpy as np

In [ ]:
# pip install pandas   -- on vscode
import pandas as pd

In [ ]:
df = pd.read_csv("/content/StudentsPerformance.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# Understanding the dataset
#default value is 5
df.head(2)# returns the first 5 rows data with the column

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

In [ ]:
df.tail(20)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
980,female,group B,high school,free/reduced,none,8,24,23
981,male,group D,some high school,standard,none,81,78,78
982,male,group B,some high school,standard,completed,79,85,86
983,female,group A,some college,standard,completed,78,87,91
984,female,group C,some high school,standard,none,74,75,82
985,male,group A,high school,standard,none,57,51,54
986,female,group C,associate's degree,standard,none,40,59,51
987,male,group E,some high school,standard,completed,81,75,76
988,female,group A,some high school,free/reduced,none,44,45,45
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# to chaeck the number of rows and columns in the dataset we use ,

df.shape

(1000, 8)

In [ ]:
# to check the name of the columns in the dataset we use ,

df.columns# returns list of columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
# to check the count of the indiviual columns with data types and null values we use,

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

object means a kind of string and integer value

In [ ]:
# to check the statistical values we use ,
# not work on
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#to check the unique values in the particular columns we use,

df['gender'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
df['parental level of education'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [ ]:
# to delete a particular column we use, and store at variable
d = df.drop('race/ethnicity',axis=1)

In [ ]:
d

,gender,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,bachelor's degree,standard,none,72,72,74
1,female,some college,standard,completed,69,90,88
2,female,master's degree,standard,none,90,95,93
3,male,associate's degree,free/reduced,none,47,57,44
4,male,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...
995,female,master's degree,standard,completed,88,99,95
996,male,high school,free/reduced,none,62,55,55
997,female,high school,free/reduced,completed,59,71,65
998,female,some college,standard,completed,68,78,77
999,female,some college,free/reduced,none,77,86,86

In [ ]:
#if i want to delete more than one column we use,

a= df.drop(['parental level of education','lunch'], axis = 1)

In [ ]:
a

,gender,race/ethnicity,test preparation course,math score,reading score,writing score
0,female,group B,none,72,72,74
1,female,group C,completed,69,90,88
2,female,group B,none,90,95,93
3,male,group A,none,47,57,44
4,male,group C,none,76,78,75
...,...,...,...,...,...,...
995,female,group E,completed,88,99,95
996,male,group C,none,62,55,55
997,female,group C,completed,59,71,65
998,female,group D,completed,68,78,77
999,female,group D,none,77,86,86

In [ ]:
# to delete the rows and columns without knowing its name we can use iloc to find the location and then drop it.
x = df.iloc[:,:-1]

In [ ]:
x

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score
0,female,group B,bachelor's degree,standard,none,72,72
1,female,group C,some college,standard,completed,69,90
2,female,group B,master's degree,standard,none,90,95
3,male,group A,associate's degree,free/reduced,none,47,57
4,male,group C,some college,standard,none,76,78
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99
996,male,group C,high school,free/reduced,none,62,55
997,female,group C,high school,free/reduced,completed,59,71
998,female,group D,some college,standard,completed,68,78
999,female,group D,some college,free/reduced,none,77,86

In [ ]:
# mapping --- assigning some other literals to a particular item or value

df['gender'] = df['gender'].map({'male' : 1, 'female' : 2})

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,2,group B,bachelor's degree,standard,none,72,72,74
1,2,group C,some college,standard,completed,69,90,88
2,2,group B,master's degree,standard,none,90,95,93
3,1,group A,associate's degree,free/reduced,none,47,57,44
4,1,group C,some college,standard,none,76,78,75

In [ ]:
# to check the null values or the missing values we use,

df.isnull()# returns false for not null and true for null values

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
df.index

RangeIndex(start=0, stop=1000, step=1)